issues:
  max-same-issues: 0
linters:
  disable-all: true
  enable: # please keep this alphabetized
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
linters-settings: # please keep this alphabetized
  goimports:
    local-prefixes: go.etcd.io # Put imports beginning with prefix after 3rd-party packages.
