---
name: Reusable Cross-Platform Build Workflow
on:
  workflow_call:
    inputs:
      archs:
        required: true
        type: string
      os:
        required: true
        type: string
permissions: read-all

jobs:
  cross-build:
    strategy:
      matrix:
        arch: ${{ fromJSON(inputs.archs) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - id: goversion
      run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ steps.goversion.outputs.goversion }}
    - name: Build for ${{ inputs.os }}/${{ matrix.arch }}
      run: |
        GOOS=${{ inputs.os }} GOARCH=${{ matrix.arch }} go build ./...
