name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f # v10.0.0
        with:
          days-before-stale: 90
          days-before-close: 21
          stale-issue-label: stale
          stale-pr-label: stale
