---
name: Tests AMD64
permissions: read-all
on: [push, pull_request]
jobs:
  test-linux-amd64:
    uses: ./.github/workflows/tests-template.yml
  test-linux-amd64-race:
    uses: ./.github/workflows/tests-template.yml
    with:
      runs-on: ubuntu-latest
      targets: "['linux-unit-test-4-cpu-race']"

  coverage:
    needs:
      - test-linux-amd64
      - test-linux-amd64-race
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - run: make coverage
