---
name: Tests ARM64
permissions: read-all
on: [push, pull_request]
jobs:
  test-linux-arm64:
    uses: ./.github/workflows/tests-template.yml
    with:
      runs-on: ubuntu-24.04-arm
  test-linux-arm64-race:
    uses: ./.github/workflows/tests-template.yml
    with:
      runs-on: ubuntu-24.04-arm
      targets: "['linux-unit-test-4-cpu-race']"

  coverage:
    needs:
      - test-linux-arm64
      - test-linux-arm64-race
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
      - run: make coverage
