---
name: Tests AMD64
permissions: read-all
on: [push, pull_request]
jobs:
  test-linux-amd64:
    uses: ./.github/workflows/tests-template.yml
  test-linux-amd64-race:
    uses: ./.github/workflows/tests-template.yml
    with:
      runs-on: ubuntu-latest
      targets: "['linux-unit-test-4-cpu-race']"

  coverage:
    needs:
      - test-linux-amd64
      - test-linux-amd64-race
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
      - run: make coverage
